name: News Mongo
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: News Mongo 
        run: curl -m 600 ${{ secrets.URL }}
